language: python
python:
  - 3.4
  - 3.5
  - 3.6
services:
  - postgresql
install:
  - pip install -qr requirements.txt
  - pip install -q coveralls
before_script:
  - psql -U postgres -c "create database travisci"
  - cd laboratorios
script:
  - coverage run --source=python manage.py test
after_success:
  - coveralls
